version: '3.5'

services:
  db:
    container_name: ${PROJECT_NAME}-db
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - project_net
    ports:
      - '5439:5432'
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

networks:
  project_net:
    name: ${PROJECT_NAME}_net

volumes:
  pgdata: